//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerikaMendoza
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.Deliveries = new HashSet<Delivery>();
        }
    
        public int ProductID { get; set; }
        public string ProductDescription { get; set; }
        public Nullable<int> ProductUnitID { get; set; }
        public Nullable<int> ProductFormID { get; set; }
        public Nullable<int> ProductTypeID { get; set; }
        public Nullable<bool> IsAntibiotic { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Delivery> Deliveries { get; set; }
        public virtual ProductForm ProductForm { get; set; }
        public virtual ProductType ProductType { get; set; }
        public virtual ProductUnit ProductUnit { get; set; }
    }
}
